src/pages/ProfilePage.js
We are already trimming with `f-ellipsis`.
=> fix: display full lightning address, is trimmed if too long

src/pages/ChatPage.tsx, src/pages/MessagesPage.tsx
The DMs screen was showing an entry for your own DM, but it contained events from every DM that you've been involved in.
I filtered out the DMs that you sent to yourself for that message, almost like the "note to self" feature on Signal.
=> filter for self dms

package.json, src/Element/Text.tsx, yarn.lock
By disallowing the annoying link/image syntax that would cause terrible rendering bugs in other clients.
As result of this change, this note:
```
- lists
- still
- work
normal https://literal.links and `monospace` still work
**bold** and _italic_ still work
just [annoying](https://syntax-heavy.links/likethis) do not work, and ![the even](https://more.annoying/images.png)
normal images work fine: https://pixy.org/src/487/4870083.jpg
```
Renders like this:
=> Make Markdown more interoperable

src/Const.ts
For eden, @Cameri has said it has a load balanced setup. For nostr-pub.semisol, it's mostly running on idle right now with 8 threads and 16GB RAM.
=> Add more relays (high performance)

src/Element/NoteTime.tsx
This is a suggestion to fix issue https://github.com/v0l/snort/issues/46
The NoteTime now renders as a `<time>` element and will show the absolute time on hover using the title attribute (similar to how GitHub does it).
I have also added a `datetime` attribute.
=> Show absolute time on hover

src/Pages/ProfilePage.tsx
It should fix https://github.com/v0l/snort/issues/176
=> bug: prepends https when missing from website

src/Element/TidalEmbed.tsx
The code was using the old unmaintained embed player. This updates the code to use the newest one via our OEmbed API: https://oembed.tidal.com/?url=https://tidal.com/browse/track/145596276
The OEmbed API delivers the embed with sizes for different embed types. `dangerouslySetInnerHTML` is a bit sad, if wanted I can refactor to instead read out sizes from the delivered iframe and set those on a new <iframe> in the component.
https://user-images.githubusercontent.com/877455/216334497-f429daa3-4cf2-4dcd-8114-a0cabfa0fec3.mov
=> Use the current embed player via TIDALs OEmbed API.

packages/app/src/Pages/Root.tsx
This PR fixes a bug that caused the app to blackout when a user who has not registered any Paid Relay selects the global tab. 
before:
after: 
this account has only `wss://relay.damus.io`.
=> Fix blackout when selecting global tab

packages/app/src/Element/Nip05.tsx, packages/app/src/Element/ProfileImage.tsx
The long profile text was overflowing of the box, so move the `f-ellipsis` to the proper.
This works for both the display name and NIP-05.
ref: https://snort.social/e/note1gp6dy9w7j4qh6asemt9ptdk4c04qfdse6dwsj296p3zlk2zy6fvqjf9ffz
before:
after:
=> Prevent profile text from overflowing flex container when it is too long

packages/app/src/Pages/Root.tsx
I think the spacing between `Read global from` and `[globalRelay]` is large and a bit misleading. Especially in Japanese, I thought.
after:
=> Reduce space between the texts for selecting relays

packages/app/src/Element/Note.css, packages/app/src/Element/NoteFooter.tsx
In order to address https://github.com/v0l/snort/issues/177, I tried adding a background menu item which closes the sub-menu. I made this menu item cover a large area near the sub-menu. If a user clicks within this area, it will close the menu rather than performing the action underneath.
Rather than cover the whole page, I kept the size smaller. If a user scrolls away from the open sub-menu, they can still interact with other buttons and features.
I also increased the width of the three vertical dots menu button, so that its easier to click. Its current width is 4px, I increased this to 16px.
Here is a visual of the component, I temporarily set the color to blue so it is visible:
https://user-images.githubusercontent.com/14062229/218881434-0f46a7b9-2ac7-4241-b70e-2a0876497eb4.mov
=> Improve overflow menu button

packages/app/src/Element/Reactions.css, packages/app/src/Element/Reactions.tsx
resolves https://github.com/v0l/snort/issues/342
The full text of the comment is shown in a popup when hovering over the text.
=> fix long zap comment text overflow

packages/app/src/Const.ts
This regex seems to cause problems in some browsers. Reverting back to what it was before for now.
=> Revert "Merge pull request #347 from v0l/fix-links-in-parentheses"

packages/nostr/src/legacy/Thread.ts
Noticed 're:' was being added to notes in the UI when it only mentioned a note. This didn't constitute a thread and shouldn't attempt to add who it is replying to in the UI since there wasn't a reply to display. This simply makes sure that a thread is detected when there is an 'e' tag and the marker for the tag is not a mention.
=> Update thread detection to not include mentions

packages/app/src/Element/UnreadCount.css
This is more of a suggestion. Not a bug. I've noticed when looking at alot of DMs, though the unread background color is different, it's not different enough to make it easy to see what messages have unreads. So I updated the color to be the purple highlight color so it sticks out more. 
Before:
After:
=> Change message unread color to purple

packages/app/src/Pages/Layout.tsx
Clicking the Mark All Read button was clearing the messages, but the purple dot was not disappearing until the page was refreshed. It appears it was just because the calculation was being cached and not updated because the dm interaction counter was not inputted as a dependency to useMemo
=> Remove unread message dot when messages all read

packages/app/src/Pages/SearchPage.tsx
This PR adds the `autofocus` attribute to the search field input element on the search page. This improves the UX especially when a user is searching and adding multiple users in a row.
=> feat: add search page field autofocus

packages/app/src/Const.ts, packages/app/src/Element/Text.tsx, packages/app/src/Util.test.ts, packages/app/src/Util.ts
This should fix the following:
- URLs in parentheses
- URLs at the end of a sentence
Some links for testing:
URLs in parenthesis - https://fix-url-parsing-edge-cases.snort-social.pages.dev/e/note1phqc0hu77psunm49fdwjfdnwmmm9pzu9tq52wrkue7gceht9cfpqmajhs3
URLs at the end of a sentence - https://fix-url-parsing-edge-cases.snort-social.pages.dev/e/note1as9axphvvkhzagx62p5qgdh6jqq93d5f3pdueqpdwkf77y7ylqts8tuue2
=> fix URL parsing edge cases

packages/app/src/Element/Note.tsx
Fixes https://github.com/v0l/snort/issues/366
* detect macOS "cmd" key in click event and open note in new tab
This would be a first easy step to enable opening notes in new tabs.
As a follow up, right click functionality could be enabled. After quick research this would probably require default a tags, which deviate from the react logic of navigating which might break other functionality.
=> feat(note): open note in new tab on cmd press

packages/app/src/Element/Skeleton.css
Fixes https://github.com/v0l/snort/issues/381 
The skeleton component had css that addressed the dark theme, this `prefers-color-scheme` media query had no effect however.
* change `prefers-color-scheme` to `html.light` selector
* improve styles for dark theme
=> fix(skeleton): dark theme styles

packages/app/src/Element/Text.tsx
When the text is:
```
http-is-great!
```
splitByUrl return `["http-is-great!"]` correctly but it always become hyper link since that does only checking only startsWith("http").
https://snort.social/e/note1dvng6smhrn5hxn8wcmyfutngusa7fqpxh93xnx8gal6w9ljjkjmss8qfu2
=> fix HyperText matching

packages/app/src/Element/Note.css, packages/app/src/Element/Note.tsx
Depending on the text, notes can be difficult to navigate to because the click/tap needs to land precisely within the bounds of the text.
This change adjusts behavior such that clicking/tapping on any non-child (excluding the aforementioned text) space within the note fires `goToEvent`.
=> Makes entire note clickable

packages/app/public/index.html, packages/app/src/Const.ts, packages/app/src/Element/HyperText.tsx, packages/app/src/Element/WavlakeEmbed.tsx
This enables the display of an embedded music player when people share links to tracks on Wavlake. The embedded player also is capable of boosting the track if the Alby extension (WebLN) is available and the wallet is capable of sending keysends. The boost button is not visible if WebLN is not available.
=> Add Wavlake embed

packages/app/src/Element/Text.tsx, packages/app/src/Feed/EventPublisher.ts
resolves https://github.com/v0l/snort/issues/418
```json
{
"content": "Testing that the word notes doesn't turn into an event mention, but nip-19 note ID does turn into a mention #[0]",
"created_at": 1678395675,
"id": "ee5f7877ee0bab89be86e5a04f005001dfddcb5a0f75240e773b1979e80e8304",
"kind": 1,
"pubkey": "cf5d1fa43cfb08f3d14bd6af9f71e68eff6359fbd8028cfcea4ab38dfbf595de",
"sig": "b7e0fea93c23f5064012927287adeb76e9be0d2ed9026113cd9879abe72d8261a6f40200447088d55304ee5a32ecab0ac52219eeaa28795f87bcbd1ae4ac6971",
"tags": [
[
"e",
"06b4abc93c300a98b5230fab289ffbbf722f6bea22dfd5c8ce6a27315706c280",
"",
"mention"
]
],
"relays": [
"wss://offchain.pub"
]
}
```
=> Fix event mention bug

packages/app/src/Element/Tabs.tsx
While working on something else, I noticed a warning in the console about the Tabs not having unique `key` attributes. This just adds that to shut React up. I doubt any performance increases actually come from this. :laughing:
=> Added key attr to Tabs to remove React warning

packages/app/src/Feed/EventPublisher.ts
resolves https://github.com/v0l/snort/issues/440
```json
{
"id": "d098bbfc7fb36cc5204012ad5db7b624e77f934f98cfd39301409c7838e0cca3",
"pubkey": "03e20803e8917f3ba4e029e6fcd2a3c1b97cdd7c691119c1bdf4bb7543e4e1c1",
"created_at": 1678826024,
"kind": 1,
"tags": [
[
"e",
"d5dc392fc5b381c526182ffdfda0ddfc4eca0b67eedbb4179bfc9f1d9bb3c7c0",
"",
"mention"
]
],
"content": "Note IDs should be replaced with a tag: \n#[0]\nOther text such as link that contain note IDs should not be replaced with a tag:\n\nhttps://snort.social/e/note16hwrjt79kwqu2fsc9l7lmgxal38v5zm8amdmg9umlj03mxanclqqn7k634\n\n",
"sig": "4e5166ff2a0a78679b01b1e71c35522cbfc481bfa76336f0ca9b938ced463a918e29966ea3d39745bc0a550ace4f1dc7ea0c46c20cace5e83f9843590707b8a4",
"relays": [
"wss://nostr-relay.alekberg.net"
]
}
```
=> only replace note ID when note ID starts with `@` character

packages/app/src/Element/Relay.tsx, packages/app/src/Pages/Root.tsx, packages/app/src/Util.test.ts, packages/app/src/Util.ts
Updated relay names to include the search property in addition to the host in order to support relays that use query parameters for filtering, such as `universe.nostrich.land`.
before:
after:
=> Display search property alongside host in relay name

packages/app/src/Element/Copy.tsx, packages/app/src/Element/HyperText.tsx, packages/app/src/Element/Mention.tsx, packages/app/src/Element/NostrLink.tsx, packages/app/src/Element/Note.tsx, packages/app/src/Element/NoteFooter.tsx, packages/app/src/Element/NoteReaction.tsx, packages/app/src/Element/ProfileImage.tsx, packages/app/src/Element/Text.tsx, packages/app/src/Element/Textarea.tsx, packages/app/src/Element/Thread.tsx, packages/app/src/Feed/ThreadFeed.ts, packages/app/src/Pages/EventPage.tsx, packages/app/src/Pages/Login.tsx, packages/app/src/Pages/NostrLinkHandler.tsx, packages/app/src/Pages/ProfilePage.tsx, packages/app/src/Pages/new/NewUserFlow.tsx, packages/app/src/Util.test.ts, packages/app/src/Util.ts, packages/app/src/nip6.ts, packages/nostr/src/legacy/Links.ts
Use `nevent` / `nprofile` links when relay data is known
- Text notes ALWAYS have relay information so share links and clicking on threads will now always use `nevent` 
- When relay hints exist for `e` tags then `nevent` links will be created (mentions or `re:` tags in note header)
- `nostr:` or `web+nostr:` links will be parsed and converted into clickable links within snort (except `naddr`)
- Profile QR now uses `nprofile` as well as offering copy link
=> Nostr links

packages/nostr/.eslintrc.cjs, packages/nostr/README.md, packages/nostr/relay/config.toml, packages/nostr/src/client/conn.ts, packages/nostr/src/client/emitter.ts, packages/nostr/src/client/index.ts, packages/nostr/src/crypto.ts, packages/nostr/test/dm.ts, packages/nostr/test/ready-state.ts, packages/nostr/test/relay-info.ts, packages/nostr/test/setup.ts, packages/nostr/test/text-note.ts
Implement a concept of ready states for the relay connections. Fetch relay info when connecting to a relay. Note, the client will not be advanced into the `OPEN` ready state until the info fetch has succeeded or failed.
Cleaned up some other unrelated stuff as well. Need a slightly cleaner approach to error handling.
=> `nostr` package: fetch relay info

packages/app/src/index.css
In some environments, texts in `<option>`/`<optgroup>` elements are invisible if the dark theme is enabled.  This problem occurs because the text color matches with the background color accidentally.
I confirmed that this problem occurred in:
- Chrome on Windows 10
- Edge on Windows 10
- Chrome on Ubuntu 22.04
- Firefox on Ubuntu 22.04
Fixed it by setting `background-color` of these elements to `--bg-color`.
I confirmed that this fix won't break appearance in other environments, such as Safari/Chrome on macOS/iOS, Chrome on Android.
=> Fix: invisible <option> text in dark theme

packages/app/src/Pages/settings/Relays.tsx
It will help with https://github.com/v0l/snort/issues/451 
We can still connect to ws when running local snort.
=> Prevents adding ws relay when over https

packages/app/src/Const.ts, packages/app/src/Element/WavlakeEmbed.tsx
We just updated our site so that the music player lives on wavlake.com. This update allows Snort to render embeds correctly for tracks/albums/artists from both the legacy player.wavlake.com links as well as the new ones.
=> Update Wavlake embed to support .com links

packages/app/src/Element/NoteCreator.tsx, packages/app/src/Element/NoteFooter.tsx, packages/app/src/Pages/Layout.tsx, packages/app/src/State/NoteCreator.ts, packages/app/src/State/Store.ts
resolves https://github.com/v0l/snort/issues/408
This fixes a bug where the modal closes while replying to a note. This happens if the thread re-renders while you are replying.
Drafts of notes are also now automatically saved unless the user clicks the cancel button.
=> use redux for NoteCreator state management

packages/app/src/Const.ts, packages/app/src/Element/WavlakeEmbed.tsx
This fixes an issue where shares from our new zine subdomain are getting blanked out because the regex is incorrectly converting them to embed links.
=> Update regex for Wavlake embeds, ignore zine subdomain

packages/app/src/Element/Text.tsx, packages/app/src/Util.test.ts, packages/app/src/Util.ts, packages/app/src/setupTests.js
resolves https://github.com/v0l/snort/issues/501
People often type the literal text `nostr:npub` when talking about nostr URIs. That shouldn't be converted to a link.
=> don't render nostr:npub as a link

packages/app/src/index.css
In some languages and resolutions, the text 'Follow' for hashtags is overflowing.
This is due to the fixed width of the button.
This PR fixes it.
Screenshot after fix:
=> fix text overflow on follow button

packages/app/src/Components/Embed/TidalEmbed.tsx
Playback won't work correctly without the `allow="encrypted-media"` attribute. Also added the sandbox attribute to improve security.
=> [TIDAL Embeds] Add allow and sandbox attributes
