v0l/snort

- src/feed/Subscription.js
- src/feed/TimelineFeed.js
- src/index.css
- src/pages/Root.css
- src/pages/Root.js
Adding global tab to root page (Home page)
I also disabled the `timeline-related` sub as its causing spam on relays, In #2 i think you mentioned that you are aware of this anyway..
> Add global tab to Root

- src/Text.js
- src/element/NoteCreator.css
- src/element/NoteCreator.js
This is how it looks like now with inline error message.
> Note creator improvement

- src/element/Nip05.css
- src/element/Nip05.js
- src/pages/ProfilePage.js
Noticed cash.app doesn't set CORS so those don't show as verified but in general the nostr.json files are CORS-ready
> feat: nip05 on profile page

- src/Const.js
- src/Text.js
- src/element/Note.css
https://snort.social/e/note1l8xjvck3cqa9ghlccf2vnsmdnp0vak7uam9h7uyqpzuggdrnj80qs0pfxq
> fix: support m.youtube.com subdomain links

- src/element/Invoice.js
- src/element/LNURLTip.js
>  Show QR code first instead of directly opening invoice on desktop
> Shows QR code first 

- package.json
- src/element/DM.tsx
- src/element/Note.css
- src/element/Note.js
- src/element/NoteCreator.css
- src/element/NoteCreator.js
- src/element/NoteFooter.js
- src/element/NoteReaction.css
- src/element/NoteReaction.js
- src/element/NoteTime.js
- src/element/ProfileImage.css
- src/element/Textarea.tsx
- src/index.css
- src/pages/ProfilePage.css
- src/pages/ProfilePage.js
- yarn.lock
A few minor UI improvements and made textarea resize dinamically.
> UI improvements

- src/element/FollowsList.tsx
- src/element/FollowsYou.tsx
- src/feed/FollowsFeed.ts
- src/pages/ProfilePage.tsx
> feat: follows you on profile page

- public/index.html
- src/Const.ts
- src/Element/Text.tsx
- src/Element/TidalEmbed.tsx
> Tidal embeds

- package.json
- src/Element/Note.css
- src/Element/NoteFooter.tsx
- src/index.css
- src/index.tsx
- yarn.lock
> Add note context menu

- public/index.html
- src/Const.ts
- src/Element/SoundCloudEmded.tsx
- src/Element/Text.tsx
https://github.com/v0l/snort/issues/98
> feat: soundcloud embed

- src/Element/FollowersList.tsx
- src/Element/FollowsList.tsx
- src/Element/FollowsYou.tsx
- src/Element/Timeline.css
- src/Element/Timeline.tsx
- src/Feed/LoginFeed.ts
- src/Feed/Subscription.ts
- src/Feed/ThreadFeed.ts
- src/Feed/TimelineFeed.ts
- src/Pages/EventPage.tsx
- src/Pages/Notifications.tsx
- src/Pages/settings/Preferences.tsx
- src/State/Login.ts
> feat: Show latest

- src/Element/FollowsYou.css
- src/Element/LNURLTip.css
- src/Element/Note.css
- src/Element/UnreadCount.css
> light theme fixes

- public/index.html
- src/Const.ts
- src/Element/MixCloudEmbed.tsx
- src/Element/Text.tsx
https://snort.social/e/note1a2fun4vxktycjngfx422zg2s429z6z9tqawhj8rdyjqd2qydyhvqvp5ew9
> adds mixcloud

- src/State/Users/Hooks.ts
- yarn.lock
My bad, broke this by accident.
> fix: default to in-memory db only on db read fail

- src/Element/Avatar.tsx
- src/Element/NoteReaction.tsx
- src/Pages/settings/Preferences.tsx
- src/State/Login.ts
Added image proxy service which:
1. Converts avatars to webp
2. Resizes avatars to 200x200 (default)
3. Caches all avatars for 12hrs
> Image proxy service

- src/Element/Avatar.tsx
- src/Element/ProxyImg.tsx
- src/Element/Text.tsx
- src/Feed/ImgProxy.ts
- src/Pages/settings/Preferences.tsx
- src/Pages/settings/Profile.tsx
- src/State/Login.ts
- src/index.css
Use standard `imgproxy` service to proxy images instead of custom ffmpeg in api, also make it configurable so that people can use their own instance
> Use standard imgproxy

- .gitignore
- public/index.html
- src/Const.ts
- src/Element/SpotifyEmbed.tsx
- src/Element/Text.tsx
resolves https://github.com/v0l/snort/issues/182
I tested embedding songs, playlists, albums, and podcasts and they all work great.
Song embed
https://open.spotify.com/track/1Sgj10byiGzPpI2IrXSFEn?si=6d15381f6d564149
https://snort.social/e/note1rk50pff7r6rhtp4xghdt4ecve82lquma3zhxfkaz564cdzrqstcsfdzgcz
Album embed
https://open.spotify.com/album/3tQd5mwBtVyxCoEo4htGAV?si=CjgdxdAATMu3Xc1YOwq7Jw
https://snort.social/e/note1k6wekcs942nav7m03gp2zpkyw88q08972caq4jutkk4wr5vn43lqv7xakz
Playlist embed
https://open.spotify.com/playlist/4SwuF39rGVg6VX3Sevgn0Y?si=c8f3e9a4dd8946f6
https://snort.social/e/note100h6uz2rkag42j99eghzyr3ppsg7fn0cpmtypwwrj3vt7swlrykqzjzzdl
Podcast embed
https://open.spotify.com/episode/4dDg0a7X2aCAcYxT3aCHOk?si=f28506a3dd4a4b8b …
> Add Spotify embed

- src/Element/Zap.css
- src/Element/Zap.tsx
> display note zaps succintly

- src/Element/LoadMore.tsx
- src/Element/Skeleton.css
- src/Element/Skeleton.tsx
- src/Element/Timeline.tsx
> Skeleton component on timeline loading for better user experience

- .babelrc
- package.json
- src/IntlProvider.tsx
- src/Pages/Layout.tsx
- src/Pages/messages.js
- src/Util.ts
- src/index.tsx
- src/translations/en.json
- src/translations/es.json
- tsconfig.json
- yarn.lock
This possibly resolves https://github.com/v0l/snort/issues/127.
Not sure what languages you want to support. I started with just English and Spanish.
The locale is being set by whatever locale the user has set in their browser. You could also maybe let the user set the locale in their user settings or with a language selector on the landing page.
English
Spanish
> react-intl spike

- config-overrides.js
- package.json
- src/Element/messages.js
- src/Pages/messages.js
- src/Pages/settings/messages.js
- src/Util.ts
- yarn.lock
@verbiricha I figured out how to get babel-plugin-react-intl-auto to auto inject the message descriptors with babel.
> add ability to use babel plugins without ejecting

- src/Pages/settings/Index.tsx
- src/Pages/settings/Relays.tsx
Hi Kieran. Thanks for supporting intl.
I found some oversight of intl, so fix them.
> oversight of intl

- src/Element/ProfileImage.tsx
> fix(missing-event): avoid redirect

- src/Pages/ChatPage.css
- src/Pages/ChatPage.tsx
resolves https://github.com/v0l/snort/issues/248
Also, fixes auto-scrolling to bottom of conversation which is not working in prod.
before:
after:
> Fix DM page UI

- src/Element/Text.tsx
https://snort.social/e/note1qdyx2rfvc8z6ky42nrx2qlh4tu8mxju8phfwagl7hyqqgjhn8cgqc3na5d
> fix: set auto to whole text content instead of individual paragraphs

- src/Nostr/Links.ts
- src/Pages/Layout.tsx
- src/Pages/NostrLinkHandler.tsx
- src/Pages/ProfilePage.tsx
- src/Util.ts
- src/index.tsx
Handle `nostr:` links
Ref #158 #159
> protocol handler

- public/index.html
- src/Const.ts
- src/Element/AppleMusicEmbed.tsx
- src/Element/HyperText.tsx
resolves https://github.com/v0l/snort/issues/284
I tested embedding songs, albums, and playlists.
Song embed
https://music.apple.com/us/album/wu-tang-clan-aint-nuthing-ta-f-wit-feat-rza-inspectah/269842381?i=269843448
Album embed
https://music.apple.com/us/album/enter-the-wu-tang-36-chambers-expanded-edition/269842381
Playlist embed
https://music.apple.com/us/playlist/wu-tang-clan-essentials/pl.877ca4b1d4dc4f24b2a7e0dc5c55b6ff
> Add Apple Music embed

- packages/app/src/Element/Note.css
> fix(fotter-actions): add highlighting and min-width

- packages/app/src/Pages/ProfilePage.tsx
> fix(profile): convert page id to npub bech32

- packages/app/src/Pages/Root.tsx
- packages/app/src/Pages/settings/Preferences.tsx
- packages/app/src/Pages/settings/messages.ts
- packages/app/src/State/Login.ts
Allows the user to select the default page to load (Posts, Convos, Global) on load.
> Add default page selector

- packages/app/src/Db/index.ts
- packages/app/src/Element/Note.tsx
- packages/app/src/Element/Timeline.tsx
- packages/app/src/Feed/Subscription.ts
- packages/app/src/Pages/Layout.tsx
- packages/app/src/Pages/Root.tsx
- packages/app/src/State/Cache.ts
- packages/app/src/State/Store.ts
- packages/app/src/Util.ts
Remove feed cache, IndexdDB is very slow, using redux cache for now until i can come up with a better solution.
Restore scroll position should also work now if you go back
> Feed cache rework

- packages/app/src/Const.ts
resolves https://github.com/v0l/snort/issues/343
> fix links in parentheses

- packages/app/src/Pages/settings/Profile.css
- packages/app/src/Pages/settings/Profile.tsx
I noticed that the profile settings page was pretty unstyled compared to the preferences page. So I just updated it a little bit to make it match that page.
> Small settings page stuff

- packages/app/public/index.html
- packages/app/src/Const.ts
- packages/app/src/Element/HyperText.tsx
- packages/app/src/Element/NostrNestsEmbed.tsx
resolves https://github.com/v0l/snort/issues/375
Not sure if it's a good idea to add this right now since Nosts Nests is still early in development and they don't actually have real embed code, but it could be a good way to get more people to check out the linked nests.
https://user-images.githubusercontent.com/3655410/222055058-31e371ce-d3bb-4a2d-9283-1c2cff0d5112.mp4
> add Nostr Nests embed

- packages/app/src/Element/Text.tsx
- packages/app/src/Element/Thread.tsx
- packages/app/src/Pages/EventPage.tsx
resolves https://github.com/v0l/snort/issues/254
https://user-images.githubusercontent.com/3655410/222245788-33803330-0700-4bf1-a4df-31795c7463ad.mp4
> Fix broken note links

- packages/app/src/Element/BackButton.css
Fixes https://github.com/v0l/snort/issues/396
> fix(BackButton): vertical align styles

- packages/app/src/Element/HyperText.tsx
resolves https://github.com/v0l/snort/issues/409
> render webm links as inline videos

- packages/app/src/Const.ts
resolves https://github.com/v0l/snort/issues/349
> render embed for youtube live links

- packages/app/src/Element/NoteReaction.tsx
- packages/nostr/src/legacy/EventKind.ts
resolves https://github.com/v0l/snort/issues/403
> do not render reposts of badge award events in timelines

- packages/app/src/Pages/settings/Preferences.tsx
resolves https://github.com/v0l/snort/issues/413
> fix NaN when parsing empty string

- packages/app/src/Pages/Root.tsx
> Shorten long relay name

- packages/nostr/src/client/conn.ts
- packages/nostr/src/client/emitter.ts
- packages/nostr/src/client/index.ts
- packages/nostr/test/simple-communication.ts
Add a simple `"eose"` event listener in the `Nostr` client.
> `nostr` package: NIP-15 "EOSE" support

- functions/e/[id].ts
- functions/p/[id].ts
- functions/tsconfig.json
- package.json
- yarn.lock
Adding basic OpenGraph tags (title/description/image)
> OpenGraph tag injection

- packages/app/src/Element/NostrFileHeader.tsx
- packages/app/src/Element/NostrLink.tsx
- packages/app/src/Element/NoteCreator.tsx
- packages/app/src/Feed/EventFeed.ts
- packages/app/src/State/NoteCreator.ts
- packages/app/src/System/EventBuilder.test.ts
- packages/app/src/System/EventBuilder.ts
- packages/app/src/Upload/VoidCat.ts
- packages/app/src/Upload/index.ts
- packages/nostr/README.md
- packages/nostr/src/legacy/EventKind.ts
- packages/nostr/src/legacy/Links.ts
Supporting NIP-94 file headers for void.cat uploader
Ref: https://github.com/nostr-protocol/nips/pull/337
Test post: https://nip94.snort-social.pages.dev/e/note1mns2hkjns8dtr724a7qfj02aw0vle6953lqh5f3zaexrztlszreqd4vmye
> NIP-94 file headers

- packages/app/src/Element/Nip5Service.tsx
- packages/app/src/Nip05/SnortServiceProvider.ts
- packages/app/src/Pages/Verification.tsx
- packages/app/src/Pages/new/GetVerified.tsx
- packages/app/src/Pages/subscribe/ManageSubscription.tsx
- packages/app/src/Pages/subscribe/SubscriptionCard.tsx
- packages/app/src/Pages/subscribe/index.tsx
- packages/app/src/SnortApi.ts
- Enable ordering handles via linked subscription
- Handle renewal for subscription and payment from "new" state
> Subscription handle

- packages/app/config/soloco.json
> feat: Add config for soloco.nl

- packages/worker-relay/src/sqlite/sqlite-relay.ts
- packages/worker-relay/src/types.ts
Adds AND filter capability re: https://github.com/nostr-protocol/nips/pull/1365
```
{ "&t": [ "4k", "movie" ] }
```
> [worker-relay] Add AND filter compatability

- packages/worker-relay/src/sqlite/sqlite-relay.ts
Was treating everything between 10000 and 40000 as a Replacable Event, this effectively broke PRE's because any given d tag couldn't exist more than once in the worker relay, regardless of which pubkey it was from.
There wasn't any noticeable performance loss on a database with 20k events (other than the whole 20k events thing)
Todo:
> [worker-relay] Add PRE and fix RE support.
